CREATE TABLE silver_ilo_data (
    REF_AREA NVARCHAR(255),
    REF_AREA_LABEL NVARCHAR(255),
    INDICATOR NVARCHAR(255),
    INDICATOR_LABEL NVARCHAR(255),
    SEX NVARCHAR(50),
    AGE NVARCHAR(100),
    FREQ NVARCHAR(50),
    FREQ_LABEL NVARCHAR(100),
    AGG_METHOD NVARCHAR(100),
    TIME_PERIOD INT,
    OBS_VALUE FLOAT
);
INSERT INTO silver_ilo_data (
    REF_AREA, REF_AREA_LABEL, INDICATOR, INDICATOR_LABEL,
    SEX, AGE, FREQ, FREQ_LABEL, AGG_METHOD, TIME_PERIOD, OBS_VALUE
)
SELECT
    REF_AREA,
    REF_AREA_LABEL,
    INDICATOR,
    INDICATOR_LABEL,
    SEX,
    AGE,
    FREQ,
    FREQ_LABEL,
    AGG_METHOD,
    TRY_CAST(TIME_PERIOD AS INT),
    TRY_CAST(OBS_VALUE AS FLOAT)
FROM staging_ilo_emp
;

